### ISSUE TITLE
Processing killed on compute canada

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#108]
with the following SLURM config:
~~~
#SBATCH --account=def-jcohen
#SBATCH --time=0-03:00        # time (DD-HH:MM)
#SBATCH --ntasks=128          # number of MPI processes
#SBATCH --mem-per-cpu=4096M   # memory; default unit is megabytes
~~~

and this YML config for sct_run_batch:
```yaml
path_data: /scratch/jcohen/data-single-subject-master
path_output: /scratch/jcohen/results
task: /home/jcohen/code/spine-generic/spine-generic/processing/process_data.sh
jobs: 128
```

i get this job killed:
~~~
/home/jcohen/code/spine-generic/spine-generic/processing/process_data.sh: line 76:  4663 Killed                  sct_deepseg_sc -i ${file}.nii.gz -c $contrast -qc ${PATH_QC} -qc-subject ${SUBJECT}
~~~

and this other job got the following error:
~~~
OSError: [Errno 12] Cannot allocate memory
~~~
