### ISSUE TITLE
Consider an alternative YAML scheme for `sg_manual_correction`

### ISSUE THREAD

**Issue by joshuacwnewton** [spine-generic/spine-generic#248]
In [spine-generic's docs](https://spine-generic.readthedocs.io/en/latest/analysis-pipeline.html#segmentation-and-vertebral-labeling), it recommends using this YAML scheme:

```yaml
FILES_SEG:
- sub-amu01_T1w_RPI_r.nii.gz
- sub-amu01_T2w_RPI_r.nii.gz
- sub-cardiff02_dwi_moco_dwi_mean.nii.gz
FILES_GMSEG:
- sub-amu01_T2star_rms.nii.gz
FILES_LABEL:
- sub-amu01_T1w_RPI_r.nii.gz
- sub-amu02_T1w_RPI_r.nii.gz
```

This was a little challenging to work with over at SCT while developing a QC report interface (https://github.com/neuropoly/spinalcordtoolbox/pull/3253) for 2 main reasons:

<details>
<summary> 1. Subjects are identified by filename only </summary>

> This works for BIDS datasets, because the subject is encoded in the filename, so each file will be unique. 
> 
> But, on the SCT side of things, if a non-BIDS dataset structure is used, it's very possible the subject is encoded in the directory name instead. So, SCT wants to use the absolute path to the image, but this is currently not compatible with `sg_manual_correction` due to how the filenames are parsed:
> 
> https://github.com/spine-generic/spine-generic/blob/6d7a6a2ef1695a3994e472aac2981dab77b0ddfd/spinegeneric/utils.py#L136

</details>

<details>
<summary> 2. There are only 3 categories (FILES_SEG/FILES_GMSEG/FILES_LABEL) </summary>

> 
> Each of these categories maps to 1 SCT function each:
> 
> https://github.com/spine-generic/spine-generic/blob/6d7a6a2ef1695a3994e472aac2981dab77b0ddfd/spinegeneric/cli/manual_correction.py#L91-L99
> 
> But, SCT tries to map _all_ SCT functions to these categories: https://github.com/neuropoly/spinalcordtoolbox/pull/3253/commits/64f68be16d02cd4307bfba2b376adf7594a61735. 
>
> The problem with this on SCT's end is, 3 categories is quite limiting, because it means the same image can show up multiple times in the same category. (For example, once for `sct_deepseg_sc`, and then another time for `sct_register_to_template`, which we've also associated with `FILES_SEG`.) 
</details>

Because of this, it might be nice if we could coordinate between SCT and spine-generic to come up with a scheme that works for both projects.
